version: '3.8'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8

    ports:
      - "2181:2181"

    volumes:
      - "zookeeper_data:/bitnami"

    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-broker:
    image: docker.io/bitnami/kafka:3.3

    ports:
      - "4092:9092"

    volumes:
      - "kafka_data:/bitnami"

    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "4080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker:9092

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
